### ISSUE TITLE
Improve warning in `align`

### ISSUE THREAD

**Issue by KittyGiraudel** [jakecleary/elf-scss#11]
Current:

> $direction must be set to either "both", "vertical, or "horizontal"

Suggested:

> `$direction` parameter must be set to either `both`, `vertical` or `horizontal`. Given: `#{$direction}`.

**Comment by jakecleary** [comment]
Ah, much nicer. Thanks mate. Will put in now. Keep these coming, you're a hero @HugoGiraudel.
