### ISSUE TITLE
Think about `transform` rather than offsets

### ISSUE THREAD

**Issue by KittyGiraudel** [jakecleary/elf-scss#12]
Out of curiosity, would not it be better to use `transform: translateX()` in `shift` mixin rather than `left`/`right`? We could benefit from hardware acceleration.

**Comment by jakecleary** [comment]
Can't see why not. Any cons off the top of your head? Can't think of any myself.

**Comment by KittyGiraudel** [comment]
IE9 support.

**Comment by jakecleary** [comment]
Just requires `-ms-` as far as I can tell. Not a problem as far as I'm concerned.

**Comment by corysimmons** [comment]
IE9 supports `translate`. Autoprefixer gets this right?

**Comment by KittyGiraudel** [comment]
Totally.

**Comment by corysimmons** [comment]
I prefer translate as well. Swapping in Stylus too.

**Comment by corysimmons** [comment]
Does `calc` work inside of `translateX`? Getting some weird results.

**Comment by jakecleary** [comment]
That's what I was wondering @corysimmons. I'm happy to switch over if that's that case :smile:

**Comment by corysimmons** [comment]
http://stackoverflow.com/a/12418064

> Mixing percentages with other value types in the calc() function within a transform doesn't seem to work at all in Chrome. I'll report this as a bug.

**Comment by corysimmons** [comment]
Yeah I think it's broken.

**Comment by jakecleary** [comment]
I can't imagine why it wouldn't...

**Comment by corysimmons** [comment]
Hold on this until Chrome fixes their bug

**Comment by jakecleary** [comment]
Ah, okay. Maybe leave until we confirm haha.

**Comment by jakecleary** [comment]
:+1:

**Comment by corysimmons** [comment]
Closing since this will probably be a real bug for years

**Comment by KittyGiraudel** [comment]
Bug has been fixed on Chrome as far as I can tell, so feel free to use it.

**Comment by corysimmons** [comment]
Testing it now and it doesn't work. =[

**Comment by KittyGiraudel** [comment]
Testing it now and it does: http://codepen.io/HugoGiraudel/pen/47071717736f0f9bea990f3b1ccdd4e0.

**Comment by corysimmons** [comment]
Not when you use multiple units

**Comment by KittyGiraudel** [comment]
Updated my pen, still works.

**Comment by corysimmons** [comment]
http://codepen.io/corysimmons/pen/azOopR

**Comment by corysimmons** [comment]
Here: http://codepen.io/corysimmons/pen/VYLZPJ

Seems screwy

**Comment by KittyGiraudel** [comment]
Dude, `1em * 4%` makes no sense. It cannot be computed, no matter where.

**Comment by corysimmons** [comment]
What about the last example? That's effectively how Elf's sizing mixins work.

**Comment by KittyGiraudel** [comment]
Everything is working fine. 

When you write `translateX(calc(100% * 1/3))`, you ask the element to be shifted to the right of one third of its own width.

When you write `left: calc(100% * 1/3)`, you ask the element to be shifted to the right of one third the width of its parent.

Because of this, the change needs a little bit more than just changing the property name. You have to rethink your calculations.

**Comment by corysimmons** [comment]
![](http://i.imgur.com/Yz4ND2N.gif)

**Comment by corysimmons** [comment]
Aren't we shifting around based on container size though?

**Comment by jakecleary** [comment]
Let's leave this until we're sure it's correct.

**Comment by jakecleary** [comment]
Obviously feel free to discuss it here, but lets not rush something in.

**Comment by jakecleary** [comment]
Closing this for now
