### ISSUE TITLE
Do we need a History.md?

### ISSUE THREAD

**Issue by corysimmons** [jakecleary/elf-scss#16]
Isn't that what releases is for?

**Comment by jakecleary** [comment]
It's only here because I'm lazy and I use a tool to generate it. Will remove.

**Comment by KittyGiraudel** [comment]
You might want to go with `CHANGELOG.md` rather than `HISTORY.md`. Seems more standard.

**Comment by corysimmons** [comment]
^ this, but even so I have to ask what the point of a separate file for this is if we're doing proper GitHub releases?
