### ISSUE TITLE
customize demo page for scss

### ISSUE THREAD

**Issue by corysimmons** [jakecleary/elf-scss#2]

**Comment by corysimmons** [comment]
done but not sure why it isn't showing up at http://jakecleary.github.io/elf-scss/ ???

**Comment by corysimmons** [comment]
also, 4 spaces? X_X @jakecleary

**Comment by jakecleary** [comment]
Not sure why it's not showing up. I'm home in an hour or 2 so will fix then :)

4 is so much nicer and seems to be more popular for scss.
