### ISSUE TITLE
use sassdoc instead of jsdoc

### ISSUE THREAD

**Issue by corysimmons** [jakecleary/elf-scss#5]

**Comment by KittyGiraudel** [comment]
Docs: http://sassdoc.com.

**Comment by jakecleary** [comment]
Will check this out and get in tonight.

**Comment by KittyGiraudel** [comment]
If you need help, be sure to ask.

**Comment by jakecleary** [comment]
Will do man, thanks. Just haven't had a chance to work on it yet. Should be free this evening (GMT) so will get it done then :smile:
