### ISSUE TITLE
Add warn in `align`

### ISSUE THREAD

**Issue by KittyGiraudel** [jakecleary/elf-scss#6]
Currently, nothing happens if `$direction` argument from `align` mixin is neither `vertical`, `horizontal` or `both`. You should probably add a warning in this case, explaining why nothing got output.

Remember, typos happen.

**Comment by corysimmons** [comment]
Ah, maybe this should default to `both`

**Comment by KittyGiraudel** [comment]
It does default to `both`, that's really not the issue. The issue is that if it's not an accepted value, nothing happens and I don't know why.

**Comment by jakecleary** [comment]
Oh makes sense. Will add a `@warn`. Gunna sort all these little bits now.
