### ISSUE TITLE
Remove/rename %cf

### ISSUE THREAD

**Issue by KittyGiraudel** [jakecleary/elf-scss#7]
`%cf` placeholder does not seem to be used. Either it should be removed, or at worst it should be renamed. As is, you are likely to override (get overrode by) a placeholder already called `%cf` which might lead to some issues.

**Comment by corysimmons** [comment]
Thoughts on `%clearfix`?

**Comment by jakecleary** [comment]
I guess it is so common that most people will already have one set up. Maybe we should just remove it? Just a nice-to-have I guess.

**Comment by KittyGiraudel** [comment]
If you don't use it, remove it.

**Comment by corysimmons** [comment]
I use it pretty frequently. Anytime I use `column` pretty much

**Comment by KittyGiraudel** [comment]
That's not the point. Either the library uses it internally (which is not currently the case), in which case it should stay, or it should be removed.

**Comment by jakecleary** [comment]
Yeah @HugoGiraudel you're right. I'll remove it :smile:

**Comment by corysimmons** [comment]
I see your point, but at the same time it's terribly handy. FINE fine!

**Comment by KittyGiraudel** [comment]
Then Elf should provide a toolkit of extra features that are not needed in the core.

**Comment by jakecleary** [comment]
Sounds good @HugoGiraudel.

**Comment by corysimmons** [comment]
Yup. Removed from Stylus version as well

**Comment by corysimmons** [comment]
Should we remove `debug()` as well then?

**Comment by jakecleary** [comment]
No not in my opinion. Seems pretty integral.

**Comment by corysimmons** [comment]
It's a utility that works with the grid system but isn't part of the grid system itself - same as clearfix

**Comment by corysimmons** [comment]
@HugoGiraudel Thoughts?

**Comment by KittyGiraudel** [comment]
Highly discutable. In a way, `debug` is more like an extra tool than an actual feature from the lib. On the other hand, it makes no sense as a standalone helper since it's supposedly dependant on the lib.

**Comment by jakecleary** [comment]
Yeah I vote we keep.

**Comment by corysimmons** [comment]
I vote if we're gonna be consistent with getting rid of utilities then it should go.

`debug` stands alone with any dev workflow as well.

**Comment by jakecleary** [comment]
Hmmm, I dunno. It feels to coupled to me. It's more than a nice-to-have. Unless we definitely want to release an elf-toolkit with some nice little tools.

**Comment by corysimmons** [comment]
Too lazy for a utility kit or to debate. Keep it. =)

**Comment by jakecleary** [comment]
Sure?

**Comment by corysimmons** [comment]
Yeah not worried about it

**Comment by jakecleary** [comment]
Okay cool.
