### ISSUE TITLE
About `$column-or-span` from `shift` and `offset`

### ISSUE THREAD

**Issue by KittyGiraudel** [jakecleary/elf-scss#8]
It is not quite clear what this argument could be aside of its default value (`column`). As far as I can see, the only relevant value is `column`. Fair enough, so shouldn't this be a boolean instead (e.g. `$column: true`)?

**Comment by corysimmons** [comment]
True

**Comment by jakecleary** [comment]
Yeah you're right, makes more sense as a bool. Will sort.

**Comment by jakecleary** [comment]
Bloody hell; I wish I could type.
