### ISSUE TITLE
Rename align() to content-align()

### ISSUE THREAD

**Issue by jakecleary** [jakecleary/elf-scss#9]
The name is a bit confusing as it aligns the content of the element you call it on, not the element itself.

Agree? Disagree?

**Comment by corysimmons** [comment]
`align-children()` better?

**Comment by KittyGiraudel** [comment]
I can see how `align-children` would help understanding.

**Comment by jakecleary** [comment]
Yeah nice. Will fix.

**Comment by corysimmons** [comment]
Done on stylus too
